notifications:
	email: false
branches:
	only: master
language: objective-c
osx_image: xcode7.3
xcode_workspace: Jenda.xcworkspace
xcode_scheme: Jenda
xcode_sdk: iphonesimulator9.3
install: pod install
